<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <UseWindowsForms>false</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\StrataScene.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\StrataScene.ico">
      <Link>assets\StrataScene.ico</Link>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StrataScene.Platform\StrataScene.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.1.4" />
  </ItemGroup>
</Project>
